version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Install Reporter
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
              chmod +x ./cc-test-reporter
            fi
      - run:
          name: Run Tests
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./cc-test-reporter before-build
            fi
            go test -v ./... -coverprofile c.out
      - run:
          name: Report
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./cc-test-reporter after-build --exit-code $?
            fi
          when: always

workflows:
  version: 2
  workflow:
    jobs:
      - test
